service: aws-node-http-api-project
frameworkVersion: '3'

provider:
  name: aws
  runtime: nodejs18.x
  region: ap-south-1

functions:
  index:
    handler: index.handler
    events:
      - httpApi:
          path: /
          method: get
  health:
    handler: health.handler
    events:
      - httpApi:
          path: /health
          method: get
